<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Plugin para el sistema de sensores de Gazebo -->
    <gazebo>
        <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
            <render_engine>ogre2</render_engine>
        </plugin>
    </gazebo>
    <gazebo>
        <plugin filename="gz-sim-imu-system"
        name="gz::sim::systems::Imu">
        </plugin>
    </gazebo>

    <!-- Plugin para el sensor LiDAR -->
    <gazebo reference="lidar_link">
        <sensor name="lidar_sensor" type="gpu_lidar">
            <always_on>1</always_on>
            <update_rate>10</update_rate>
            <topic>/scan</topic>
            <visualize>1</visualize>
            <lidar>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.14159</min_angle>
                        <max_angle>3.14159</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.1</min>
                    <max>12.0</max>
                    <resolution>0.01</resolution>
                </range>
            </lidar>
        </sensor>
    </gazebo>
    <!-- IMU -->

    <gazebo reference="imu_link">
    <sensor name="imu_sensor" type="imu">
        <always_on>1</always_on>
        <update_rate>50</update_rate>
        <topic>/imu/data</topic>
        <imu>
          <!-- El bloque <imu> solo contiene el modelo de ruido -->
          <angular_velocity>
            <x>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>0.0</stddev>
                <bias_mean>0.0</bias_mean>
                <bias_stddev>0.0</bias_stddev>
              </noise>
            </x>
            <y>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>0.0</stddev>
                <bias_mean>0.0</bias_mean>
                <bias_stddev>0.0</bias_stddev>
              </noise>
            </y>
            <z>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>0.0</stddev>
                <bias_mean>0.0</bias_mean>
                <bias_stddev>0.0</bias_stddev>
              </noise>
            </z>
          </angular_velocity>
          <linear_acceleration>
            <x>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>0.0</stddev>
                <bias_mean>0.0</bias_mean>
                <bias_stddev>0.0</bias_stddev>
              </noise>
            </x>
            <y>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>0.0</stddev>
                <bias_mean>0.0</bias_mean>
                <bias_stddev>0.0</bias_stddev>
              </noise>
            </y>
            <z>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>0.0</stddev>
                <bias_mean>0.0</bias_mean>
                <bias_stddev>0.0</bias_stddev>
              </noise>
            </z>
          </linear_acceleration>
        </imu>
    </sensor>
</gazebo>

    <!-- Plugin para el controlador de tracción diferencial (DiffDrive) -->
    <gazebo>
        <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
            <!-- Juntas de las ruedas izquierdas -->
            <left_joint>wheel_fl_joint</left_joint>
            <left_joint>wheel_rl_joint</left_joint>
            <!-- Juntas de las ruedas derechas -->
            <right_joint>wheel_fr_joint</right_joint>
            <right_joint>wheel_rr_joint</right_joint>
            <!-- Cinemática -->
            <wheel_separation>${chassis_ylength + wheel_width}</wheel_separation>
            <wheel_radius>${wheel_radius}</wheel_radius>
            <!-- Tópicos -->
            <topic>/cmd_vel</topic>
            <odom_topic>/odom</odom_topic>
            <tf_topic>/tf_internal_sim</tf_topic>
            <odom_frame_id>mi_robot/odom</odom_frame_id>
            <odom_child_frame_id>mi_robot/robot_root</odom_child_frame_id>
            <robot_base_frame>robot_root</robot_base_frame>
            <publish_odom>true</publish_odom>
            <publish_odom_tf>false</publish_odom_tf>
            <publish_wheel_tf>false</publish_wheel_tf>
        </plugin>
    </gazebo>

</robot>