<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Plugin para el sistema de sensores de Gazebo -->
    <gazebo>
        <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
            <render_engine>ogre2</render_engine>
        </plugin>
    </gazebo>

    <!-- Plugin para el sensor LiDAR -->
    <gazebo reference="lidar_link">
        <sensor name="lidar_sensor" type="lidar">
            <always_on>1</always_on>
            <update_rate>10</update_rate>
            <topic>/scan</topic>
            <visualize>true</visualize>
            <lidar>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.14159</min_angle>
                        <max_angle>3.14159</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.1</min>
                    <max>12.0</max>
                    <resolution>0.01</resolution>
                </range>
            </lidar>
        </sensor>
    </gazebo>

    <!-- Plugin para el controlador de tracción diferencial (DiffDrive) -->
    <gazebo>
        <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
            <!-- Juntas de las ruedas izquierdas -->
            <left_joint>wheel_fl_joint</left_joint>
            <left_joint>wheel_rl_joint</left_joint>
            <!-- Juntas de las ruedas derechas -->
            <right_joint>wheel_fr_joint</right_joint>
            <right_joint>wheel_rr_joint</right_joint>
            <!-- Cinemática -->
            <wheel_separation>${chassis_ylength + wheel_width}</wheel_separation>
            <wheel_radius>${wheel_radius}</wheel_radius>
            <!-- Tópicos -->
            <topic>/cmd_vel</topic>
            <odom_topic>/odom</odom_topic>
            <tf_topic>/tf</tf_topic>
        </plugin>
    </gazebo>

</robot>