<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mi_robot">

  <!-- Reusable Properties -->
  <!-- Chassis-->
  <xacro:property name="chassis_xlength" value="0.265"/>
  <xacro:property name="chassis_ylength" value="0.094"/>
  <xacro:property name="chassis_zlength" value="0.073"/>
  <xacro:property name="chassis_mass" value="0.670"/>
  <xacro:property name="chassis_zOffset" value="0.015"/>
 
  <!-- Backwards-compatible aliases for older property names -->
  <xacro:property name="chassis_length" value="${chassis_xlength}"/>
  <xacro:property name="chassis_width" value="${chassis_ylength}"/>
  <xacro:property name="chassis_height" value="${chassis_zlength}"/>
  <!-- keep both spellings of zOffset (original had a typo) -->
  <xacro:property name="chassis_zOfffset" value="${chassis_zOffset}"/>

  <!-- Wheels-->
  <xacro:property name="wheel_radius" value="0.0325"/>
  <xacro:property name="wheel_width" value="0.028"/>
  <xacro:property name="wheel_xoffset" value="0.055"/>
  <xacro:property name="wheel_yoffset" value="${chassis_ylength/2 + wheel_width/2}"/>
  <xacro:property name="wheel_mass" value="0.032"/>
  <xacro:property name="wheel_Izz" value="${0.5*wheel_mass*wheel_radius*wheel_radius}"/>
  <xacro:property name="wheel_Ixx" value="${(1.0/12.0)*wheel_mass*(3.0*wheel_radius*wheel_radius + wheel_width*wheel_width)}"/>
  <xacro:property name="wheel_Iyy" value="${wheel_Ixx}"/>
  <xacro:property name="wheel_Ixz" value="0"/>

<!-- LiDAR-->
  <xacro:property name="lidar_length" value="0.04"/>
  <xacro:property name="lidar_radius" value="0.035"/>
  <xacro:property name="lidar_mass" value="0.05"/>
  <xacro:property name="lidar_Izz" value="${0.5*lidar_mass*lidar_radius*lidar_radius}"/>
  <xacro:property name="lidar_Ixx" value="${(1.0/12.0)*lidar_mass*(3.0*lidar_radius*lidar_radius + lidar_length*lidar_length)}"/>
  <xacro:property name="lidar_Iyy" value="${lidar_Ixx}"/>
  

  <!-- Constants (avoid redefining common symbols) -->
  <xacro:property name="pi" value="3.14159265358979323846"/>
  <!-- Chasis -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${chassis_xlength} ${chassis_ylength} ${chassis_zlength}"/>
      </geometry>
      <origin xyz="0 0 ${chassis_zOffset}" rpy="0 0 0"/>
      <material name="gray"><color rgba="0.5 0.5 0.5 1"/></material>
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_xlength} ${chassis_ylength} ${chassis_zlength}"/>
      </geometry>
      <origin xyz="0 0 ${chassis_zOffset}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <origin xyz="0 0 ${chassis_zOffset}" rpy="0 0 0"/>
      <mass value="${chassis_mass}"/>
      <inertia
        ixx="${chassis_mass*(chassis_ylength*chassis_ylength + chassis_zlength*chassis_zlength)/12.0}"
        ixy="0"
        ixz="0"
        iyy="${chassis_mass*(chassis_xlength*chassis_xlength + chassis_zlength*chassis_zlength)/12.0}"
        iyz="0"
        izz="${chassis_mass*(chassis_xlength*chassis_xlength + chassis_ylength*chassis_ylength)/12.0}"/>
    </inertial>
  </link>

  <!-- Dummy root link to avoid KDL warning about inertia on root link -->
  <link name="robot_root">
    <!-- intentionally no inertial element here; KDL does not support inertia on the root link -->
  </link>

  <joint name="robot_root_joint" type="fixed">
    <parent link="robot_root"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Macro for a wheel -->
  <xacro:macro name="wheel_macro" params="wheel_name x y">
    <link name="${wheel_name}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"><color rgba="0 0 0 1"/></material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="${wheel_mass*(3.0*wheel_radius*wheel_radius + wheel_width*wheel_width)/12.0}"
          ixy="0"
          ixz="0"
          iyy="${wheel_mass*(3.0*wheel_radius*wheel_radius + wheel_width*wheel_width)/12.0}"
          iyz="0"
          izz="${0.5*wheel_mass*wheel_radius*wheel_radius}"/>
      </inertial>
    </link>

    <joint name="${wheel_name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${wheel_name}_link"/>
      <origin xyz="${x} ${y} ${-chassis_height/8}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="1.0" velocity="30"/>
    </joint>
  </xacro:macro>

  <!-- Ruedas (invocar macro) -->
  <xacro:wheel_macro wheel_name="wheel_fl" x="${wheel_xoffset}" y="${wheel_yoffset}"/>
  <xacro:wheel_macro wheel_name="wheel_fr" x="${wheel_xoffset}" y="${-wheel_yoffset}"/>
  <xacro:wheel_macro wheel_name="wheel_rl" x="${-wheel_xoffset}" y="${wheel_yoffset}"/>
  <xacro:wheel_macro wheel_name="wheel_rr" x="${-wheel_xoffset}" y="${-wheel_yoffset}"/>

  <!-- LiDAR -->
  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
      </geometry>
      <material name="green"><color rgba="0 1 0 1"/></material>
     </visual>
    <collision>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${lidar_mass}"/>
      <inertia
        ixx="${lidar_Ixx}"
        ixy="0"
        ixz="0"
        iyy="${lidar_Iyy}"
        iyz="0"
        izz="${lidar_Izz}"/>
    </inertial>
  </link>
  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 ${chassis_height/2.0 + lidar_length/2.0}" rpy="0 0 0"/>
  </joint>
  <!-- Sensor delantero -->
  <link name="sensor_front_link">
    <visual>
      <geometry>
        <cylinder radius="0.03" length="0.02"/>
      </geometry>
      <material name="red"><color rgba="1 0 0 1"/></material>
    </visual>
  </link>
  <joint name="sensor_front_joint" type="fixed">
    <parent link="base_link"/>
    <child link="sensor_front_link"/>
    <origin xyz="${(chassis_length/2.0) + 0.02} 0 ${chassis_height/2.0}" rpy="0 0 0"/>
  </joint>

  <!-- Sensor trasero -->
  <link name="sensor_back_link">
    <visual>
      <geometry>
        <cylinder radius="0.03" length="0.02"/>
      </geometry>
      <material name="blue"><color rgba="0 0 1 1"/></material>
    </visual>
  </link>
  <joint name="sensor_back_joint" type="fixed">
    <parent link="base_link"/>
    <child link="sensor_back_link"/>
    <origin xyz="${-(chassis_length/2.0 + 0.02)} 0 ${chassis_height/2.0}" rpy="0 0 0"/>
  </joint>

<!--gazebo-->
<plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
  <render_engine>ogre2</render_engine>
</plugin>

<gazebo reference= "lidar_link">
  <sensor name="gpu_lidar" type = "gpu_lidar"> <!--if there's no gpu just use ray-->
    	<pose> 0 0 0 0 0 0 </pose>
    	<visualize> true </visualize>
    	<update_rate> 10 </update_rate>
		<topic> scan </topic>
    	<lidar>
			<scan>
				<horizontal>
					<samples> 360 </samples>
					<resolution> 1 </resolution>
					<min_angle> ${-pi} </min_angle>
					<max_angle> ${pi} </max_angle>
				</horizontal>
			</scan>
			<range>
				<min> 0.3 </min>
				<max> 12 </max>
				<resolution> 0.01 </resolution>
			</range>
		    <noise>
				<type> gaussian </type>
				<mean> 0.0 </mean>
				<stddev> 0.01 </stddev>
			</noise>
		</lidar>
		<always_on> true </always_on>
		<visualize> true </visualize>
		
    </sensor>
</gazebo>

	  

    


</robot>
