bt_navigator:
  ros__parameters:
    global_frame: map
    robot_base_frame:  mi_robot/robot_root
    transform_tolerance: 0.5
    default_nav_to_pose_bt_xml: "$(find-pkg-share nav2_bt_navigator)/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml"
    default_nav_through_poses_bt_xml: "$(find-pkg-share nav2_bt_navigator)/behavior_trees/navigate_through_poses_w_replanning_and_recovery.xml"
    navigators:
      - navigate_to_pose
      - navigate_through_poses
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"

planner_server:
  ros__parameters:
    expected_planner_frequency: 10.0
    planner_plugins:
      - GridBased
    GridBased:
      plugin:  "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown:  true

controller_server:
  ros__parameters:
    controller_frequency:  20.0
    controller_plugins:
      - FollowPath
    progress_checker_plugins:
      - progress_checker
    goal_checker_plugins:
      - goal_checker
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.05
      movement_time_allowance: 8.0
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.05
      yaw_goal_tolerance: 0.2
      stateful: true
    FollowPath:
      plugin:  "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: false
      min_vel_x: 0.0
      max_vel_x: 0.25
      max_vel_theta: 1.0
      acc_lim_x: 2.5
      acc_lim_theta: 3.2
      decel_lim_x: -2.5
      decel_lim_theta: -3.2
      vx_samples: 20
      vtheta_samples: 40
      sim_time: 1.2
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.2
      xy_goal_tolerance: 0.05
      trans_stopped_velocity: 0.15
      stateful: true
      critics:
        - RotateToGoal
        - Oscillation
        - BaseObstacle
        - GoalAlign
        - PathAlign
        - PathDist
        - GoalDist
      BaseObstacle. scale: 0.02
      PathAlign.scale: 24.0
      PathAlign.forward_point_distance: 0.1
      GoalAlign.scale: 18.0
      GoalAlign. forward_point_distance: 0.1
      RotateToGoal.scale: 24.0
      RotateToGoal.slowing_factor: 5.0

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: mi_robot/odom
      robot_base_frame: mi_robot/robot_root
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      robot_radius: 0.11
      plugins:
        - obstacle_layer
        - inflation_layer
      obstacle_layer:
        plugin:  "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "LaserScan"
      inflation_layer:
        plugin:  "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.45
        cost_scaling_factor: 5.0
      always_send_full_costmap: false

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame:  mi_robot/robot_root
      transform_tolerance: 0.5
      robot_radius: 0.11
      resolution: 0.05
      track_unknown_space: true
      plugins:
        - static_layer
        - obstacle_layer
        - inflation_layer
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
      obstacle_layer:
        plugin:  "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan: 
          topic: /scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "LaserScan"
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.45
        cost_scaling_factor: 5.0
      always_send_full_costmap: true

map_server:
  ros__parameters:
    yaml_filename: ""

map_saver:
  ros__parameters: 
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default:  0.65
    map_subscribe_transient_local:  true

behavior_server:
  ros__parameters: 
    behavior_plugins:
      - spin
      - backup
      - drive_on_heading
      - wait
    local_frame: mi_robot/odom
    global_frame: map
    robot_base_frame: mi_robot/robot_root
    simulate_ahead_time: 1.5
    max_rotational_vel: 1.0
    min_rotational_vel: 0.35

waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: true
      waypoint_pause_duration: 2000

velocity_smoother:
  ros__parameters:
    smoothing_frequency: 20.0
    scale_velocities: false
    max_velocity: 
      - 0.4
      - 0.0
      - 2.5
    min_velocity:
      - -0.4
      - 0.0
      - -2.5
    max_accel:
      - 2.5
      - 0.0
      - 3.2
    max_decel:
      - -2.5
      - 0.0
      - -3.2
    odom_topic: "/odometry/filtered"
    odom_duration: 0.1
    enable_stamped_cmd_vel:  true

collision_monitor:
  ros__parameters:
    base_frame_id: "mi_robot/robot_root"
    odom_frame_id: "mi_robot/odom"
    cmd_vel_in_topic: "cmd_vel"
    cmd_vel_out_topic: "cmd_vel_smoothed"
    state_topic: "collision_monitor_state"
    transform_tolerance: 0.5
    source_timeout: 0.5
    base_shift_correction: true
    stop_pub_timeout: 2.0
    enable_stamped_cmd_vel: true
    observation_sources: 
      - scan
    scan: 
      type: "scan"
      topic: "/scan"
      enabled: true
    polygons:
      - PolygonStop
      - PolygonSlow
    PolygonStop:
      type: "circle"
      radius: 0.12
      action_type: "stop"
      min_points: 4
      visualize: true
      enabled: true
    PolygonSlow:
      type:  "polygon"
      points:  "[[0.2, 0.15], [0.2, -0.15], [-0.15, -0.15], [-0.15, 0.15]]"
      action_type: "slowdown"
      slowdown_ratio: 0.4
      visualize: true
      enabled: true

docking_server:
  ros__parameters: 
    controller_frequency: 50.0
    initial_perception_timeout: 5.0
    wait_charge_timeout: 5.0
    dock_approach_timeout: 30.0
    undock_linear_tolerance: 0.05
    undock_angular_tolerance:  0.1
    max_retries: 3
    base_frame:  "mi_robot/robot_root"
    fixed_frame: "mi_robot/odom"
    dock_backwards: false
    dock_plugins:
      - simple_charging_dock
    simple_charging_dock: 
      plugin:  "opennav_docking::SimpleChargingDock"
      docking_threshold: 0.05
      staging_pose: 
        - 0.0
        - 0.0
        - 0.0