<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mi_robot">

  <!-- Reusable Properties -->
  <!-- Chassis-->
  <xacro:property name="chassis_xlength" value="0.265"/>
  <xacro:property name="chassis_ylength" value="0.094"/>
  <xacro:property name="chassis_zlength" value="0.073"/>
  <xacro:property name="chassis_mass" value="0.670"/>
  <xacro:property name="chassis_zOfffset" value="0.015"/>
 
  <!-- Wheels-->
  <xacro:property name="wheel_radius" value="0.0325"/>
  <xacro:property name="wheel_width" value="0.028"/>
  <xacro:property name="wheel_xoffset" value="0.055"/>
  <xacro:property name="wheel_yoffset" value="${chassis_ylength/2 + wheel_width/2}"/>
  <xacro:property name="wheel_mass" value="0.032"/>
  <xacro:property name="wheel_Izz" value="${0.5*wheel_mass*wheel_radius*wheel_radius}"/>
  <xacro:property name="wheel_Ixx" value="${(1.0/12.0)*wheel_mass*(3.0*wheel_radius*wheel_radius + wheel_width*wheel_width)}"/>
  <xacro:property name="wheel_Iyy" value="${wheel_Ixx}"/>
  <xacro:property name="wheel_Ixz" value="0"/>

  <!-- Constants-->
  <xacro:property name="pi" value="3.1415926535"/>
 
  <!-- Chasis -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${chassis_xlength} ${chassis_ylength} ${chassis_zlength}"/>
      </geometry>
      <origin xyz="0 0 ${chassis_zOfffset}" rpy="0 0 0"/>
      <material name="gray"><color rgba="0.5 0.5 0.5 1"/></material>
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_xlength} ${chassis_ylength} ${chassis_zlength}"/>
      </geometry>
      <origin xyz="0 0 ${chassis_zOfffset}" rpy="0 0 0"/>
    </collision>
    <inertial>
    <origin xyz="0 0 ${chassis_zOfffset}" rpy="0 0 0"/>
      <mass value="${chassis_mass}"/>
      <inertia 
      ixx="$1/12*(chassis_ylength^2 + chassis_zlength^2)*chassis_mass" 
      ixy="0" 
      ixz="0" 
      iyy="$1/12*(chassis_xlength^2 + chassis_zlength^2)*chassis_mass" 
      iyz="0" 
      izz="$1/12*(chassis_xlength^2 + chassis_ylength^2)*chassis_mass"/>
    </inertial>
  </link>

  <!-- Macro for a wheel -->
  <xacro:macro name="wheel_macro" params="wheel_name x y">
    <link name="${wheel_name}_link">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"><color rgba="0 0 0 1"/></material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia 
        ixx="$1/12*(3*wheel_radius^2 + wheel_width^2)*wheel_mass" 
        ixy="0" 
        ixz="0" 
        iyy="$1/12*(3*wheel_radius^2 + wheel_width^2)*wheel_mass" 
        iyz="0" 
        izz="$1/2*wheel_radius^2*wheel_mass"/>
      </inertial>
    </link>

    <joint name="${wheel_name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${wheel_name}_link"/>
      <origin xyz="${x} ${y} ${-chassis_height/2}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- Ruedas (invocar macro) -->
  <xacro:wheel_macro wheel_name="wheel_fl" x="${wheel_xoffset}" y="${wheel_yoffset}"/>
  <xacro:wheel_macro wheel_name="wheel_fr" x="${wheel_xoffset}" y="${-wheel_yoffset}"/>
  <xacro:wheel_macro wheel_name="wheel_rl" x="${-wheel_xoffset}" y="${wheel_yoffset}"/>
  <xacro:wheel_macro wheel_name="wheel_rr" x="${-wheel_xoffset}" y="${-wheel_yoffset}"/>

  <!-- Sensor delantero -->
  <link name="sensor_front_link">
    <visual>
      <geometry>
        <cylinder radius="0.03" length="0.02"/>
      </geometry>
      <material name="red"><color rgba="1 0 0 1"/></material>
    </visual>
  </link>
  <joint name="sensor_front_joint" type="fixed">
    <parent link="base_link"/>
    <child link="sensor_front_link"/>
    <origin xyz="${chassis_length/2 + 0.02} 0 ${chassis_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- Sensor trasero -->
  <link name="sensor_back_link">
    <visual>
      <geometry>
        <cylinder radius="0.03" length="0.02"/>
      </geometry>
      <material name="blue"><color rgba="0 0 1 1"/></material>
    </visual>
  </link>
  <joint name="sensor_back_joint" type="fixed">
    <parent link="base_link"/>
    <child link="sensor_back_link"/>
    <origin xyz="-${chassis_length/2 + 0.02} 0 ${chassis_height/2}" rpy="0 0 0"/>
  </joint>

</robot>
